# Generated by Django 6.0 on 2025-12-10 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100, verbose_name='Twoja nazwa wycieczki')),
                ('trip_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Twój budżet')),
                ('start_date', models.DateField(verbose_name='Data początku wycieczki')),
                ('end_date', models.DateField(verbose_name='Data zakończenia wycieczki')),
                ('trip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Opis wydatku')),
                ('amout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota wydatku')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('food', 'Jedzenie'), ('accomodation', 'Zakwaterowanie'), ('entertainment', 'Rozrywka'), ('other', 'Inne')], default='other', max_length=20, verbose_name='Kategoria wydatku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kto płacił')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wydatki', to='core.trip')),
            ],
        ),
    ]
