# Generated by Django 6.0 on 2025-12-14 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
