# Generated by Django 6.0 on 2025-12-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trip_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktywna?'),
        ),
    ]
