# Generated by Django 6.0 on 2025-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amout_pln',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kwota wydatku w PLN'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polski Złoty'), ('EUR', 'Euro'), ('USD', 'Dolar Amerykański'), ('GBP', 'Funt Brytyjski')], default='PLN', max_length=3, verbose_name='Waluta'),
        ),
    ]
