# Generated by Django 6.0 on 2025-12-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_amout_pln_expense_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amout_pln',
            new_name='amount_pln',
        ),
    ]
